# Sonokai Maia palette
palette = "sonokai_maia"

[palettes.sonokai_maia]
red = "#f76c7c"
orange = "#f3a96a"
yellow = "#e3d367"
green = "#9cd57b"
blue = "#78cee9"
purple = "#baa0f8"
fg = "#e1e2e3"
bg = "#273136"
grey = "#82878b"

format = """
$directory\
$git_branch\
$git_status\
$python\
$nodejs\
$cmd_duration\
$line_break\
$character"""

[directory]
style = "bold blue"
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = " [$branch]($style)"
style = "yellow"

[git_status]
format = "[$all_status$ahead_behind]($style) "
style = "red"
ahead = " ↑${count}"
behind = " ↓${count}"
diverged = " ↑${ahead_count}↓${behind_count}"
modified = " ✗"
staged = " +"
untracked = " ?"
stashed = " ≡"

[python]
format = " [${virtualenv}]($style)"
style = "green"
detect_extensions = []

[nodejs]
format = " [ $version]($style)"
style = "green"

[cmd_duration]
min_time = 2_000
format = " [$duration]($style)"
style = "grey"

[character]
success_symbol = "[❯](bold blue)"
error_symbol = "[❯](bold red)"
